In [1]:
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 29 20:36:09 2020

@author: LAXMIPRIYAA
"""

import random

import numpy as np

from numpy.random import choice

from collections import Counter

import pandas as pd

class Queenboard:

  def __init__(self,mutation,totalPopulation,crossOver,generation):

   self.mutation = mutation

   self.totalPopulation = totalPopulation

   self.crossOver = crossOver

   self.fitnessScore=0

   self.populationValue = []

   self.fitnessvalue = []

   self.generation=generation

   self.alpha_list=[0,1,2,3,4,5,6,7]
   

  def create_initial_population(self):

    self.secure_random = random.SystemRandom()

    for outloop in range(self.totalPopulation):

      randomData = []

      fitnessScore = 0

      for inloop in range(len(self.alpha_list)):

        selectedData = self.secure_random.choice(self.alpha_list)

        randomData.append(selectedData)

      self.fitnessScore=self.getFitnessScore(randomData)

      self.populationValue.append(randomData)

      self.fitnessvalue.append(self.fitnessScore)

      probability = []

      probDF = pd.DataFrame({'String':self.populationValue,'FitnessScore':self.fitnessvalue})

      probDF = probDF.sort_values(['FitnessScore'],ascending=False)

      probDF = probDF.reset_index(drop=True)

    return probDF

  def print_solution(self):
      finalsequence = self.sequence[(self.sequence['FitnessScore']==28)]
      print(finalsequence) 

  
  def getFitnessScore(self,data):

    '''

    The maximum possible clahses is 28. (14 row +columns and 14 diagoinal clases )

    '''

    clashes=0

    rwclashes=len(data) - len(np.unique(data))

    clashes+=rwclashes

    for i in range(len(data)):

      for j in range(len(data)):

        if (i!=j):

          dx = abs(i-j)

          dy=abs(data[i]-data[j])

          if (dx==dy):

            clashes+=1

    fitnessScore = 28 - clashes

    return fitnessScore

  def process_mutation(self,probDF):

    self.solved=False

    crossOverPoint = 4

    print(crossOverPoint)

    print(self.generation)

    for loop in range(self.generation):

     fit=[]

     fit.append(probDF[0:1]["String"].values[0])

     fit.append(probDF[1:2]["String"].values[0])

      #print('Fitness Scores of Parents ',getFitnessScore(fit[0]),getFitnessScore(fit[1]))

     if (self.getFitnessScore(fit[0])==28| self.getFitnessScore(fit[1])==28):

       self.sequence=pd.DataFrame({'Solution':fit[0:2],'FitnessScore':[self.getFitnessScore(fit[0]),self.getFitnessScore(fit[1])]})

       print("solution", fit[0],' ',fit[1])

       self.solved=True

       break

     child1 = fit[0][0:crossOverPoint]+fit[1][crossOverPoint:]

     child2 = fit[1][0:crossOverPoint]+fit[0][crossOverPoint:]

     child1[random.randint(0,7)] =  self.secure_random.choice(self.alpha_list)

     child2[random.randint(0,7)] =  self.secure_random.choice(self.alpha_list)

     self.populationValue.append(child1)

     self.populationValue.append(child2)

     self.fitnessvalue = []

     self.totalPopulation = len(self.populationValue)

     for outloop in range(self.totalPopulation):
         
         self.fitnessScore = self.getFitnessScore(self.populationValue[outloop])

         self.fitnessvalue.append(self.fitnessScore)

     probability = []

     probDF = pd.DataFrame({'String':self.populationValue,'FitnessScore':self.fitnessvalue})

     probDF = probDF.sort_values(['FitnessScore'],ascending=False)

     probDF = probDF.reset_index(drop=True)

     print('Generation ','Average Fitness Score ',probDF["FitnessScore"].mean(),'child1:',probDF[0:1]["String"].values[0],'child2:',probDF[1:2]["String"].values[0])

  #print('Generation ',loop,' ',' Average Fitness Score ',probDF["FitnessScore"].mean())

    return self.solved

 
if (__name__ == '__main__'):
    
    ge=Queenboard(.01,150,0.5,1200)
    
    pd1=ge.create_initial_population()
    
    pd1.head()

    solution=ge.process_mutation(pd1)

if (solution == True):

  ge.print_solution()

else:
    
    print("repeat the generation to solve the equation") 
 

4
1200
Generation  Average Fitness Score  16.585526315789473 child1: [4, 6, 0, 5, 7, 0, 3, 3] child2: [5, 7, 2, 0, 6, 1, 0, 6]
Generation  Average Fitness Score  16.623376623376622 child1: [4, 6, 0, 5, 7, 0, 3, 3] child2: [3, 6, 0, 5, 5, 0, 0, 6]
Generation  Average Fitness Score  16.69871794871795 child1: [4, 6, 0, 5, 7, 0, 3, 3] child2: [1, 3, 0, 7, 4, 1, 5, 1]
Generation  Average Fitness Score  16.68354430379747 child1: [4, 6, 0, 5, 7, 0, 3, 3] child2: [3, 6, 0, 5, 5, 0, 0, 6]
Generation  Average Fitness Score  16.74375 child1: [4, 6, 0, 5, 7, 0, 3, 3] child2: [6, 1, 4, 1, 7, 0, 3, 3]
Generation  Average Fitness Score  16.82716049382716 child1: [4, 6, 0, 5, 7, 0, 3, 3] child2: [4, 6, 0, 5, 7, 0, 6, 3]
Generation  Average Fitness Score  16.902439024390244 child1: [4, 6, 0, 5, 7, 0, 6, 3] child2: [4, 6, 0, 5, 7, 0, 3, 3]
Generation  Average Fitness Score  17.018072289156628 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 0, 5, 7, 0, 3, 3]
Generation  Average Fitness Score  17.11904761

Generation  Average Fitness Score  20.45859872611465 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 1, 5, 7, 0, 6, 3]
Generation  Average Fitness Score  20.490506329113924 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 1, 5, 7, 0, 6, 3]
Generation  Average Fitness Score  20.51572327044025 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 1, 5, 7, 0, 6, 3]
Generation  Average Fitness Score  20.5375 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 1, 5, 7, 0, 0, 3]
Generation  Average Fitness Score  20.5527950310559 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 1, 5, 7, 0, 6, 3]
Generation  Average Fitness Score  20.574074074074073 child1: [4, 6, 1, 5, 7, 0, 0, 3] child2: [4, 6, 1, 5, 7, 0, 6, 3]
Generation  Average Fitness Score  20.595092024539877 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 1, 5, 2, 0, 6, 3]
Generation  Average Fitness Score  20.621951219512194 child1: [4, 6, 1, 5, 7, 0, 6, 3] child2: [4, 6, 1, 5, 7, 0, 6, 3]
Generation  Average Fitness Score  20.636363636363637 c

In [2]:
import numpy as np

sample = [4, 6, 1, 5, 2, 0, 7, 3]

samplematrix = np.zeros([8,8],dtype=np.int8)

for loop in range(8):

    samplematrix[sample[loop]][loop] = '1'

print(samplematrix)

[[0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]]
